export const coreToolModes = ['select', 'pan', 'scale', 'shoreline'] as const;

export const dockElementToolModes = [
  'floating_dock',
  'stationary_dock',
  'ramp_with_rails',
  'ramp_without_rails',
  'steps',
  'roof_overlay',
  'boat_lift',
  'riprap',
  'armour_stone',
  'dimension_line',
] as const;

export const genericShapeToolModes = [
  'shape_line',
  'shape_arrow_line',
  'shape_double_arrow_line',
  'shape_elbow_connector',
  'shape_double_elbow_connector',
  'shape_elbow_arrow_connector',
  'shape_rectangle',
  'shape_rounded_rectangle',
  'shape_callout',
  'shape_oval',
  'shape_circle',
  'shape_triangle',
  'shape_right_triangle',
  'shape_diamond',
  'shape_parallelogram',
  'shape_trapezoid',
  'shape_pentagon',
  'shape_hexagon',
  'shape_octagon',
  'shape_cross',
  'shape_plus',
  'shape_cube',
  'shape_cylinder',
  'shape_right_arrow',
  'shape_left_arrow',
  'shape_up_arrow',
  'shape_down_arrow',
  'shape_left_right_arrow',
  'shape_up_down_arrow',
  'shape_chevron_right',
  'shape_chevron_left',
] as const;

export const objectToolModes = [...dockElementToolModes, ...genericShapeToolModes] as const;

export type ToolMode = (typeof coreToolModes)[number] | (typeof objectToolModes)[number];

const editorTools = [...coreToolModes, ...objectToolModes] as const;

export const toolLabels: Record<ToolMode, string> = {
  select: 'select',
  pan: 'pan',
  scale: 'scale',
  shoreline: 'shoreline',
  floating_dock: 'floating dock',
  stationary_dock: 'stationary dock',
  ramp_with_rails: 'ramp with rails',
  ramp_without_rails: 'ramp without rails',
  steps: 'steps',
  roof_overlay: 'roof overlay',
  boat_lift: 'boat lift',
  riprap: 'riprap stone',
  armour_stone: 'armour stone',
  dimension_line: 'dimension line',
  shape_line: 'line',
  shape_arrow_line: 'arrow line',
  shape_double_arrow_line: 'double arrow line',
  shape_elbow_connector: 'elbow connector',
  shape_double_elbow_connector: 'double elbow connector',
  shape_elbow_arrow_connector: 'arrow elbow connector',
  shape_rectangle: 'rectangle',
  shape_rounded_rectangle: 'rounded rectangle',
  shape_callout: 'callout',
  shape_oval: 'oval',
  shape_circle: 'circle',
  shape_triangle: 'triangle',
  shape_right_triangle: 'right triangle',
  shape_diamond: 'diamond',
  shape_parallelogram: 'parallelogram',
  shape_trapezoid: 'trapezoid',
  shape_pentagon: 'pentagon',
  shape_hexagon: 'hexagon',
  shape_octagon: 'octagon',
  shape_cross: 'cross',
  shape_plus: 'plus',
  shape_cube: 'cube',
  shape_cylinder: 'cylinder',
  shape_right_arrow: 'right arrow',
  shape_left_arrow: 'left arrow',
  shape_up_arrow: 'up arrow',
  shape_down_arrow: 'down arrow',
  shape_left_right_arrow: 'left right arrow',
  shape_up_down_arrow: 'up down arrow',
  shape_chevron_right: 'right chevron',
  shape_chevron_left: 'left chevron',
};

export default editorTools;
